Add small text rendering for overstacked items
samolego/ClientStorage pull request #9
Opened 2022-10-20 01:51 UTC by EnderLord0042

This adds small text rendering for overstacked items.
![2022-10-19_18 47 05](https://user-images.githubusercontent.com/55165281/196836979-1cb07b4b-86b1-4330-ab7b-1680c7e6d6c6.png)

The small text rendering only applies to overstacked items. In AE2 or Refined Storage, all items in storage have their count rendered in small text. I was not able to acheive this however, because all item rendering modifications are done through mixins in this mod. Therefore, there is no way to differentiate between an item rendered in the ClientStorage GUI and an item rendered anywhere else.

2022-10-20 05:17 UTC, samolego commented
What a champ!

> There's no way to differentiate between item rendered in Clientstorage GUI vs other gui

There actually is ;) 
https://github.com/samolego/ClientStorage/blob/b0e7d8109b2b58f5a8b0ecd0c8fc9601557d998c/fabric-client/src/main/java/org/samo_lego/clientstorage/fabric_client/mixin/screen/MAbstractContainerScreen.java#L45

This is the if condition which makes it apply only to items, that are inside of clientstorage gui.

Afaik you could just move https://github.com/samolego/ClientStorage/blob/b0e7d8109b2b58f5a8b0ecd0c8fc9601557d998c/fabric-client/src/main/java/org/samo_lego/clientstorage/fabric_client/mixin/screen/MAbstractContainerScreen.java#L49 before the if, and move the assignment to true outside the inner if (but still inside the RemoteSlot instance checker).

2022-10-20 05:18 UTC, samolego commented
Something like 
![Screenshot_20221020-071720_Firefox~2](https://user-images.githubusercontent.com/34912839/196862412-5e46c413-ef62-40aa-8e7b-4ae018ed0785.png)

2022-10-20 05:22 UTC, samolego requested changes
As commented, could you apply smaller rendering for all items whose slot is instanceof RemoteSlot? Thanks

2022-10-20 23:03 UTC, EnderLord0042 commented
I did what you suggested (and fixed an issues caused by countLabel being null), and it is working for all remote slots now.
![2022-10-20_16 01 18](https://user-images.githubusercontent.com/55165281/197075029-becdbc62-0dec-4c8c-bd8c-e989618e1247.png)

2022-10-21 00:06 UTC, EnderLord0042 commented
Should the text be normal sized if the merge stacks setting is disabled?

2022-10-21 00:28 UTC, EnderLord0042 commented
Also, in refined storage, when you hold shift, the storage is sort of frozen, which lets you get stacks of 0 until you release shift. These stacks of 0 have their count label rendered in red.
![2022-10-21_00 23 14](https://user-images.githubusercontent.com/55165281/197083899-169b1a77-f4b7-4e79-bd6b-8e8eba59c33b.png)
(Image for reference)

Should I render stacks of 0 in red, in case you are planning on adding this feature in the future?

2022-10-21 05:41 UTC, samolego commented
> Should the text be normal sized if the merge stacks setting is disabled?

I'd say no, although ... I guess that could be decided up to the user actually. You can create a new boolean in config (showed in display category) that allows you to toggle it? Then the condition for small text would be merge stacks enabled or config.smallerTextRendering.

2022-10-21 05:42 UTC, samolego approved these changes

2022-10-21 06:15 UTC, samolego commented
> Also, in refined storage, when you hold shift, the storage is sort of frozen, which lets you get stacks of 0 until you release shift. These stacks of 0 have their count label rendered in red.

Actually never played with refined storage before 😅 ... So when you take all items out, the stack is still displayed, but it's actually empty?
If so, I'd say there's no need for this feature.

2022-10-21 07:37 UTC, EnderLord0042 commented
The feature in refined storage that I was mentioning is that the ordering of stacks in storage doesn't change while you are holding shift. This feature allows you to spam shift click a stack in storage without it moving. Without this feature, if you had the items in storage sorted by quantity, and you were spam shift clicking, the ordering of items in storage would change. This would lead to you partially filling your inventory with the desired item, and then filling your inventory with a different item when the slot ordering and thus the hovered item change. A consequence of the ordering not changing is that if you shift click away the last items of an item type from storage, that item will still show up with a red 0 to prevent you from shift clicking the next slot.

I find this feature of refined storage extremely useful when I am trying to fill my inventory with a specific item. If you are trying to mimic an AE2/Refined storage interface, you may want to add this feature. I was asking if you would like me to make the item label show up as red if an itemstack has 0 items so that you can mimic this behavior in the future.

2022-10-21 19:56 UTC, samolego commented
Oh, I see ... Current sorting is done per-registry, so that this doesn't happen. Due to how the mod works internally, I'm not sure I'll enable "huge" transfers via shift, as that would result in a lot of packet spam :/ ...

2022-10-22 11:46 UTC, samolego commented
Is there anything else you'd change here, or are you fine with merging :wink: ?

2022-10-22 18:40 UTC, EnderLord0042 commented
I think it is good to merge, if we want any changes to the way text is displayed later, we can make another PR for whatever we want to change.

2022-10-23 06:58 UTC, merged